# Site settings
title: 
email: eberhard_frank@me.com
author: Eberhard Frank
description: Innovation & Design
url:

# Build settings
permalink: :title/
sass:
  sass_dir: css

# Social icons
show_social_icons: true
github_username: ebefrank
twitter_username: ebefrank

# plugins
plugins: [jekyll-paginate]
paginate: 3
